Show command-line usage when document loading fails.
* src/qlom.cc: main(): Show the command-line usage if something fails,
  to give the user a clue about how to get things right.
* src/gui/main_window.[h|cc]:
  receiveError: Call QApplication::exit() instead of exit(),
  which should allow main() to continue, to show the command-line
  usage. That is still not ideal, and for some reason it doesn't, so:
  Add an isValid() member, allowing main() to know if the
  constructor worked, so it can show the command-line usage if it fails.
* src/qlom_document.h: loadDocument(): Document the filepath as
  an absolute filepath.
* src/qlom_error.h: Add a TODO noting that severity is not useful in an
  an exception, because it is for the catcher to decide, not the thrower.